### ISSUE TITLE
Registration with Unique Emails

### ISSUE THREAD

**Issue by andrewfam** [lambdalisue/django-inspectional-registration#11]
I've been trying the registration form with unique emails but it is still letting in not unique emails. My urls.py is as below

from registration.forms import RegistrationFormUniqueEmail
from registration.views import RegistrationView

class RegistrationViewUniqueEmail(RegistrationView):
    form_class = RegistrationFormUniqueEmail

urlpatterns = patterns('',
    url(r'^$','homepage.views.index'),

```
url(r'^register/$', RegistrationViewUniqueEmail.as_view(), name='registration_register'),
url('^registration/', include('registration.urls')),
```

)

**Comment by mick-t** [comment]
I think that should be added to the docs as I had a similar problem and found the solution in this issue.

**Comment by lambdalisue** [comment]
Writing English doc. It is always really tough job for me...

**Comment by mick-t** [comment]
I'll volunteer! I'll clone the repo and add the instructions and if you
like I can fix any typos or misspellings if you like.

On Fri, Feb 26, 2016 at 12:11 PM, Alisue <notifications@github.com> wrote:

> Writing English doc. It is always really tough job for me...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lambdalisue/django-inspectional-registration/issues/11#issuecomment-189376302>
> .
>



-- 
Mick Timony
---
Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better. --
S. Beckett
---

**Comment by lambdalisue** [comment]
> I'll volunteer! I'll clone the repo and add the instructions and if you like I can fix any typos or misspellings if you like.

That helps me a lot thanks :-)
I'll add some information about doc in #61 so feel free to ask me :-)
