### ISSUE TITLE
Not all template files are copied when I install this package

### ISSUE THREAD

**Issue by san89kalp** [lambdalisue/django-inspectional-registration#39]
When I install this package (tried both ways pip and by git), it does not copies some files like registration_email_subject.txt. I am using ubuntu and I am looking in this location

Using loader django.template.loaders.app_directories.Loader:
/home/myname/.virtualenvs/envname/local/lib/python2.7/site-packages/registration/templates/registration/registration_email_subject.txt (File does not exist).

When I copy these files from GIT to this directory above, it works. But it shouldn't be the case. Installation just copies 8 files. However, template in github have a total of 16 files.

**Comment by lambdalisue** [comment]
You were right! I forgot to add `*.txt`, thanks! (It is fixed in 0.5.0)
