### ISSUE TITLE
How to include default fields in the user model like first_name and last_name in registration page?

### ISSUE THREAD

**Issue by san89kalp** [lambdalisue/django-inspectional-registration#40]
I see that there are some default fields in user model like first_name and last_name. However in registration, I get to submit only two things - username and email. How can I add these two default fields of the user model in the registation page?

**Comment by giginet** [comment]
@san89kalp Hi! 

`DefaultRegistrationBackend` may help you to change registration form.
You implement custom backend and override `get_registration_form_class`. then you can use your own registration form.

See detail for the documentations. 

https://django-inspectional-registration.readthedocs.org/en/latest/registration.backends.default.html#registration.backends.default.DefaultRegistrationBackend

These also may help you.

https://github.com/kawazrepos/Kawaz3rd/blob/develop/src/kawaz/core/registrations/backends.py
https://github.com/kawazrepos/Kawaz3rd/blob/develop/src/kawaz/settings.py#L157

**Comment by san89kalp** [comment]
Hi giginet, 

Thanks for your help. That worked quite well in the direction. I am now able to display a form with First Name and Last Name. However, when I register, the data is not saved in the database - auth_user table. For achieving that, I tried to override the "register" method in backend.py file by providing two additional fields for firstname and last name. However I bumped into error - 

"register() takes at least 6 arguments (5 given)"

Could you please help me figure out with saving these two additional fields in the database.

**Comment by san89kalp** [comment]
Okay, I solved this issue. For anyone else who is looking for similar solution, I would like to add it here - 
I also overrode register method from the same class DefaultRegistrationBackend. In this method, I used these lines to save FN and LN in the database.

        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()

**Comment by robalvsan** [comment]
I'm trying this solution, but when I try to override the register method I'm having this exception:

      register() takes exactly 1 argument (5 given)

Probably I'm using incorrect syntax. 

     def register(self):
        first_name = request.POST.get('first_name')        
        new_user.first_name = first_name
        new_user.save()

What would be the correct syntax?

**Comment by lambdalisue** [comment]
See https://django-inspectional-registration.readthedocs.org/en/latest/registration.backends.default.html#registration.backends.default.DefaultRegistrationBackend.register
And you may want to see the code https://django-inspectional-registration.readthedocs.org/en/latest/_modules/registration/backends/default.html#DefaultRegistrationBackend.register

Then

```python
def register(self, username, email, request, supplement=None, send_email=None):
    new_user = super().register(username, email, request, supplement, send_email)
    # what ever you want
    return new_user
```
