### ISSUE TITLE
How to include captcha on 3 invalid login attempts in User Registration form?

### ISSUE THREAD

**Issue by sankalpanand** [lambdalisue/django-inspectional-registration#41]
I am using this package. I want to implement a captcha for 3 or more invalid login attempts. How can I do that?

Any help is greatly appreciated. Thanks.

**Comment by lambdalisue** [comment]
This library is for registration. Not for authentication.

**Comment by san89kalp** [comment]
Yeah, I understand. I need some guidance how can I extend this library to implement a capcha in the user registration page.

**Comment by lambdalisue** [comment]
Well, I'm not really sure but you can use any kind of plugins to do that I guess.

**Comment by san89kalp** [comment]
I achieved to implement capcha to the user registration form. Just for anyone else who might be looking for the same, please read Bronx's answer in this post- 
http://stackoverflow.com/questions/2275806/easy-to-use-django-captcha-or-registration-app-with-captcha

Now, yet to implement showing capcha only after 3 invalid login attempts.
