### ISSUE TITLE
Django 1.8: django.contrib.admin.util is deprecated

### ISSUE THREAD

**Issue by coredumperror** [lambdalisue/django-inspectional-registration#45]
In Django 1.8, django-inspectional-registration's use of `django.contrib.admin.util` triggers a deprecation warning. Instead, `registration/admin/__init__.py` should be using `django.contrib.admin.utils` (notice the "s" at the end.

Since this is a one-character fix, I figured doing a pull request was overkill. The only place this needs to be fixed is `registration/admin/__init__.py`.

**Comment by lambdalisue** [comment]
Thanks for reporting. Well it is not actually one-character fix thus could you confirm #46

**Comment by coredumperror** [comment]
Oh right, you need to worry about being compatible with older Django versions. I wouldn't have even thought of that, so a pull request from me would have been deceptively incomplete.

That change looks great to me.

**Comment by lambdalisue** [comment]
Ok, I'll merge it
