### ISSUE TITLE
Cannot load RegistrationSupplementBase on 0.6.0

### ISSUE THREAD

**Issue by giginet** [lambdalisue/django-inspectional-registration#58]
In 0.5.0, we can import `RegistrationSupplementBase` from `registration.supplements` but it is not available in 0.6.0.

https://github.com/lambdalisue/django-inspectional-registration/pull/55/files#diff-418b7fc88daf62eb48b8408c38a666efL11

**Comment by giginet** [comment]
We should add test cases

**Comment by lambdalisue** [comment]
Due to the new Django's limitation, it is not allowed to import from `registration.supplements`.
