### ISSUE TITLE
custom login view

### ISSUE THREAD

**Issue by stushurik** [lambdalisue/django-inspectional-registration#78]
I'd like to use custom login view https://docs.djangoproject.com/en/1.8/_modules/django/contrib/auth/views/#login.
What is the best way for doing that ?

**Comment by lambdalisue** [comment]
That is a matter of the django. This library is for registration and not for authentication.

**Comment by stushurik** [comment]
yes, but registration.urls contains /login url, and it is mapped to auth.login view.
I'd like to map that url to another view. 
I am talking about https://github.com/lambdalisue/django-inspectional-registration/blob/master/src/registration/urls.py#L50

It seems that it is hardcoded into library

**Comment by lambdalisue** [comment]
Well https://github.com/lambdalisue/django-inspectional-registration#backward-incompatibility helps? Assigning `False` to `REGISTRATION_DJANGO_AUTH_URLS_ENABLE` skip the `/login` or whatever.

I may don't get what your problem.

**Comment by stushurik** [comment]
Yes, this is it. Thank you.
