### ISSUE TITLE
Override RegistrationProfile Admin

### ISSUE THREAD

**Issue by nysbc** [lambdalisue/django-inspectional-registration#83]
Is there a good way to extend the RegistrationAdmin? It looks like it is the model admin is called if 'registration' is in INSTALLED_APPS, but if I remove 'registration' I can't import the RegistrationAdmin.

**Comment by lambdalisue** [comment]
I don't really get what you want to do. Could you explain your situation deeply?

**Comment by nysbc** [comment]
We occasionally have to modify usernames to clean up after unicode character conversion. I would like to be able to edit the username from the Registration Profile admin, either by making the existing username field editable, or by adding an inline User model admin to the RegistrationAdmin, similar to how the inline Registration Supplement admin is displayed.

Does that make sense?

**Comment by nysbc** [comment]
I discovered that I can do `admin.site.unregister(RegistrationProfile)`, I did this incorrectly the first time around. Thanks!

**Comment by lambdalisue** [comment]
Nice.
